# Database related envs
METADATA_DB_URL = "ALPHATRION_METADATA_DB_URL"
METADATA_INIT_TABLES = "ALPHATRION_METADATA_INIT_TABLES"

# Artifact storage related envs
ENABLE_ARTIFACT_STORAGE = "ALPHATRION_ENABLE_ARTIFACT_STORAGE"
ARTIFACT_REGISTRY_URL = "ALPHATRION_ARTIFACT_REGISTRY_URL"
ARTIFACT_INSECURE = "ALPHATRION_ARTIFACT_INSECURE"

# ClickHouse related envs
ENABLE_TRACING = "ALPHATRION_ENABLE_TRACING"
CLICKHOUSE_INIT_TABLES = "ALPHATRION_CLICKHOUSE_INIT_TABLES"
CLICKHOUSE_URL = "ALPHATRION_CLICKHOUSE_URL"
CLICKHOUSE_DATABASE = "ALPHATRION_CLICKHOUSE_DATABASE"
CLICKHOUSE_USERNAME = "ALPHATRION_CLICKHOUSE_USERNAME"
CLICKHOUSE_PASSWORD = "ALPHATRION_CLICKHOUSE_PASSWORD"
CLICKHOUSE_ENABLE_BATCH = "ALPHATRION_CLICKHOUSE_ENABLE_BATCH"

# Dashboard only related envs
DASHBOARD_USER_ID = "ALPHATRION_DASHBOARD_USER_ID"

# Runtime related envs
ROOT_PATH = "ALPHATRION_ROOT_PATH"
AUTO_CLEANUP = "ALPHATRION_AUTO_CLEANUP"
