METADATA_DB_URL = "ALPHATRION_METADATA_DB_URL"
INIT_METADATA_TABLES = "ALPHATRION_INIT_METADATA_TABLES"
ENABLE_ARTIFACT_STORAGE = "ALPHATRION_ENABLE_ARTIFACT_STORAGE"
ARTIFACT_REGISTRY_URL = "ALPHATRION_ARTIFACT_REGISTRY_URL"
ARTIFACT_INSECURE = "ALPHATRION_ARTIFACT_INSECURE"
ENABLE_TRACING = "ALPHATRION_ENABLE_TRACING"
ROOT_PATH = "ALPHATRION_ROOT_PATH"
AUTO_CLEANUP = "ALPHATRION_AUTO_CLEANUP"

# Dashboard only related envs
DASHBOARD_USER_ID = "ALPHATRION_DASHBOARD_USER_ID"
