apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: alphatrion
spec:
  ports:
  - port: 8123
    targetPort: 8123
    name: http
  - port: 9000
    targetPort: 9000
    name: tcp
  selector:
    app: clickhouse
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
  namespace: alphatrion
spec:
  serviceName: clickhouse
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
      - name: clickhouse
        image: clickhouse/clickhouse-server:24.3-alpine
        ports:
        - containerPort: 8123
          name: http
        - containerPort: 9000
          name: tcp
        env:
        - name: CLICKHOUSE_DB
          value: "alphatrion_traces"
        - name: CLICKHOUSE_USER
          value: "alphatrion"
        - name: CLICKHOUSE_PASSWORD
          value: "alphatrion"
        - name: CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT
          value: "1"
        volumeMounts:
        - name: clickhouse-data
          mountPath: /var/lib/clickhouse
        resources:
          requests:
            cpu: 500m
            memory: 2Gi
          limits:
            cpu: 2000m
            memory: 4Gi
  volumeClaimTemplates:
  - metadata:
      name: clickhouse-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: gp3
      resources:
        requests:
          storage: 100Gi
