"""add duration for run

Revision ID: 0f417c7cf4d3
Revises: 766c8b7fe6c5
Create Date: 2026-03-02 20:20:56.486059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f417c7cf4d3'
down_revision: Union[str, Sequence[str], None] = '766c8b7fe6c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('duration', sa.Float(), nullable=True, comment='Duration of the run in seconds'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'duration')
    # ### end Alembic commands ###
