"""add indexes

Revision ID: 766c8b7fe6c5
Revises: 344adc5da83a
Create Date: 2026-03-02 12:22:37.129491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '766c8b7fe6c5'
down_revision: Union[str, Sequence[str], None] = '344adc5da83a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_experiment_label_lookup', 'experiment_labels', ['experiment_id', 'label_name', 'label_value'], unique=False)
    op.create_index('idx_experiment_team_active_time', 'experiments', ['team_id', 'is_del', 'created_at'], unique=False)
    op.create_index('idx_experiment_team_name', 'experiments', ['team_id', 'name', 'is_del'], unique=False)
    op.create_index('idx_metric_experiment_time', 'metrics', ['experiment_id', 'created_at'], unique=False)
    op.create_index('idx_metric_run_time', 'metrics', ['run_id', 'created_at'], unique=False)
    op.create_index('idx_run_experiment_active', 'runs', ['experiment_id', 'is_del', 'created_at'], unique=False)
    op.create_index('idx_run_team_active', 'runs', ['team_id', 'is_del'], unique=False)
    op.create_index(op.f('ix_team_members_user_id'), 'team_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_members_user_id'), table_name='team_members')
    op.drop_index('idx_run_team_active', table_name='runs')
    op.drop_index('idx_run_experiment_active', table_name='runs')
    op.drop_index('idx_metric_run_time', table_name='metrics')
    op.drop_index('idx_metric_experiment_time', table_name='metrics')
    op.drop_index('idx_experiment_team_name', table_name='experiments')
    op.drop_index('idx_experiment_team_active_time', table_name='experiments')
    op.drop_index('idx_experiment_label_lookup', table_name='experiment_labels')
    # ### end Alembic commands ###
