apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alphatrion.server.fullname" . }}
  labels:
    {{- include "alphatrion.server.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  {{- if not .Values.postgresql.existingSecret }}
  # PostgreSQL password
  postgres-password: {{ .Values.postgresql.password | quote }}
  {{- end }}
  {{- if and .Values.clickhouse.enabled (not .Values.clickhouse.existingSecret) }}
  # ClickHouse password
  clickhouse-password: {{ .Values.clickhouse.password | quote }}
  {{- end }}
  {{- if and .Values.registry.enabled (not .Values.registry.existingSecret) }}
  # Docker Registry credentials
  registry-username: {{ .Values.registry.username | quote }}
  registry-password: {{ .Values.registry.password | quote }}
  {{- end }}
