apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alphatrion.server.fullname" . }}
  labels:
    {{- include "alphatrion.server.labels" . | nindent 4 }}
data:
  # Logging configuration
  ALPHATRION_LOG_LEVEL: {{ .Values.server.env.logLevel | quote }}

  # Root path for API
  {{- if .Values.server.env.rootPath }}
  ALPHATRION_ROOT_PATH: {{ .Values.server.env.rootPath | quote }}
  {{- end }}

  # Auto cleanup configuration
  ALPHATRION_AUTO_CLEANUP: {{ .Values.server.env.autoCleanup | quote }}

  # Database configuration
  ALPHATRION_METADATA_INIT_TABLES: {{ .Values.postgresql.initTables | quote }}

  # Tracing configuration
  ALPHATRION_ENABLE_TRACING: {{ .Values.server.env.enableTracing | quote }}
  {{- if .Values.clickhouse.enabled }}
  ALPHATRION_CLICKHOUSE_URL: {{ printf "http://%s:%d" .Values.clickhouse.host (int .Values.clickhouse.port) | quote }}
  ALPHATRION_CLICKHOUSE_DATABASE: {{ .Values.clickhouse.database | quote }}
  ALPHATRION_CLICKHOUSE_USERNAME: {{ .Values.clickhouse.username | quote }}
  ALPHATRION_CLICKHOUSE_INIT_TABLES: {{ .Values.clickhouse.initTables | quote }}
  ALPHATRION_CLICKHOUSE_ENABLE_BATCH: {{ .Values.clickhouse.enableBatch | quote }}
  {{- end }}

  # Artifact storage configuration
  ALPHATRION_ENABLE_ARTIFACT_STORAGE: {{ .Values.server.env.enableArtifactStorage | quote }}
  {{- if .Values.registry.enabled }}
  ALPHATRION_ARTIFACT_REGISTRY_URL: {{ .Values.registry.url | quote }}
  ALPHATRION_ARTIFACT_INSECURE: {{ .Values.registry.insecure | quote }}
  {{- end }}
